 language: cpp
 distro: bionic

 compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake llvm-dev libicu-dev

 before_script:
   - mkdir build
   - cd build
   - cmake ..

 script: make
