 language: cpp
 dist: bionic

 compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libicu-dev lcov

 before_script:
   - mkdir build
   - cd build
   - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
   - cmake --build . --config Debug -- -j $(nproc)
   - ctest -j $(nproc) --output-on-failure

 script: make
 
 after_success:
   - cd build
   - lcov --directory . --capture --output-file coverage.info
   - lcov --remove coverage.info '/usr/*' 'test/*' --output-file coverage.info
   - lcov --list coverage.info
   - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
