 language: cpp
 dist: bionic

 compiler: gcc
  
 cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages:
     - lcov
     - cmake
     - libicu-dev
  
 install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

 script:
   - mkdir build
   - cd build
   - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
   - cmake --build . --config Debug -- -j $(nproc)
   - ctest -j $(nproc) --output-on-failure
 
 after_success:
   - cd build
   - lcov --directory . --capture --output-file coverage.info
   - lcov --remove coverage.info '/usr/*' 'test/*' --output-file coverage.info
   - lcov --list coverage.info
   - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
